# Generated by Django 4.1 on 2022-08-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('flowered', models.BooleanField(default=False)),
                ('feed_repeat_every', models.CharField(choices=[(0, 'never'), (1, '1 hour'), (2, '1 day'), (3, '1 week'), (4, '1 month'), (5, 'every 2 days'), (7, 'every 2 weeks')], default=0, max_length=200)),
                ('water_repeat_every', models.CharField(choices=[(0, 'never'), (1, '1 hour'), (2, '1 day'), (3, '1 week'), (4, '1 month'), (5, 'every 2 days'), (7, 'every 2 weeks')], default=0, max_length=200)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_feed_date', models.DateTimeField(verbose_name='date for next refeed')),
                ('scheduled_water_date', models.DateTimeField(verbose_name='date for next water')),
                ('last_feed', models.DateTimeField(blank=True, null=True, verbose_name='date last fed')),
                ('last_water', models.DateTimeField(blank=True, null=True, verbose_name='date last watered')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.plant')),
            ],
        ),
    ]
