# Generated by Django 4.1 on 2022-08-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='feed_repeat_every',
            field=models.CharField(choices=[('0', 'never'), ('1', '1 hour'), ('2', '1 day'), ('3', '1 week'), ('4', '1 month'), ('5', 'every 2 days'), ('7', 'every 2 weeks')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_repeat_every',
            field=models.CharField(choices=[('0', 'never'), ('1', '1 hour'), ('2', '1 day'), ('3', '1 week'), ('4', '1 month'), ('5', 'every 2 days'), ('7', 'every 2 weeks')], default='0', max_length=200),
        ),
    ]
