# Generated by Django 4.1 on 2022-08-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_plant_feed_repeat_every_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='feed_repeat_every',
            field=models.CharField(choices=[('0', 'never'), ('1', '1 hour'), ('2', '1 day'), ('3', '1 week'), ('4', '1 month'), ('5', 'every 2 days'), ('6', 'every 2 weeks')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_repeat_every',
            field=models.CharField(choices=[('0', 'never'), ('1', '1 hour'), ('2', '1 day'), ('3', '1 week'), ('4', '1 month'), ('5', 'every 2 days'), ('6', 'every 2 weeks')], default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_plant', to='reminders.plant'),
        ),
        migrations.AlterField(
            model_name='scheduledplant',
            name='scheduled_feed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date for next refeed'),
        ),
        migrations.AlterField(
            model_name='scheduledplant',
            name='scheduled_water_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date for next water'),
        ),
    ]
